# Generated by Django 5.1.3 on 2025-04-30 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BusLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('stations', models.JSONField()),
                ('price', models.PositiveIntegerField()),
                ('interval', models.PositiveIntegerField(help_text='发车间隔(分钟)')),
                ('speed', models.FloatField(help_text='运行速度(公里/小时)')),
            ],
        ),
    ]
